#!/usr/bin/env bash
# mps_start.sh — bring up the NVIDIA CUDA MPS daemon (daemon-first, worker-capped).
# =============================================================================
# WHY MPS: nanochat training is launch-bound (~85% per-launch overhead at our
# depths), so the speedup lever is packing several training processes onto ONE
# GPU. CUDA MPS (Multi-Process Service) funnels all those processes through a
# single GPU context (`nvidia-cuda-mps-server`) so their kernels run truly
# concurrently instead of time-slicing.
#
# TWO GUARDRAILS (learned the hard way — see /workspace/mps/MPS.md on the pod):
#   1. DAEMON-FIRST: the control daemon must be up BEFORE any worker starts, or
#      the first worker grabs an exclusive context and the rest serialize. This
#      script is the thing you run first.
#   2. WORKER-CAP: MPS does NOT partition GPU *memory* — N workers share it. Cap
#      worker count / batch size so the sum fits, and optionally cap each client's
#      SM share via MPS_THREAD_PCT. An OOM under MPS can wedge the whole context.
#
# Run this ON THE POD (Linux + CUDA), once per container (MPS state lives in
# /tmp and resets on Stop->Start, which is fine — just re-run).
#
# USAGE
#   bash server_setup/mps_start.sh                 # start on GPU 0, default pipe dir
#   MPS_GPUS=0 MPS_THREAD_PCT=50 bash server_setup/mps_start.sh   # cap each client to 50% SMs
#   bash server_setup/mps_start.sh --restart       # tear down an existing daemon first
#
# KNOBS (env-overridable)
#   MPS_GPUS=0                 # CUDA_VISIBLE_DEVICES for the daemon (single GPU is the common case)
#   MPS_THREAD_PCT=<unset>     # if set (1-100), default active-thread % per client (SM cap)
#   CUDA_MPS_PIPE_DIRECTORY=/tmp/nvidia-mps        # control pipe (clients must share this)
#   CUDA_MPS_LOG_DIRECTORY=/tmp/nvidia-mps-log     # daemon/server logs
#   MPS_ENV_FILE=/tmp/mps_env.sh                   # written for workers to `source`
# =============================================================================
set -euo pipefail

GPUS="${MPS_GPUS:-0}"
THREAD_PCT="${MPS_THREAD_PCT:-}"
export CUDA_VISIBLE_DEVICES="$GPUS"
export CUDA_MPS_PIPE_DIRECTORY="${CUDA_MPS_PIPE_DIRECTORY:-/tmp/nvidia-mps}"
export CUDA_MPS_LOG_DIRECTORY="${CUDA_MPS_LOG_DIRECTORY:-/tmp/nvidia-mps-log}"
ENV_OUT="${MPS_ENV_FILE:-/tmp/mps_env.sh}"

RESTART=0
[ "${1:-}" = "--restart" ] && RESTART=1

command -v nvidia-cuda-mps-control >/dev/null 2>&1 || {
    echo "ERROR: nvidia-cuda-mps-control not found. MPS ships with the CUDA driver — is this a CUDA host?"; exit 1; }
command -v nvidia-smi >/dev/null 2>&1 || { echo "ERROR: nvidia-smi not found."; exit 1; }

mkdir -p "$CUDA_MPS_PIPE_DIRECTORY" "$CUDA_MPS_LOG_DIRECTORY"

is_running() { pgrep -x nvidia-cuda-mps-control >/dev/null 2>&1; }

# Write a sourceable env file so worker shells/launchers connect to THIS daemon.
# (Clients of the same user with the default pipe dir connect automatically, but
# this makes a non-default pipe dir / GPU selection explicit and copy-pasteable.)
write_env () {
    {
        echo "# Generated by server_setup/mps_start.sh — source this in every MPS worker shell."
        echo "export CUDA_VISIBLE_DEVICES=$CUDA_VISIBLE_DEVICES"
        echo "export CUDA_MPS_PIPE_DIRECTORY=$CUDA_MPS_PIPE_DIRECTORY"
        echo "export CUDA_MPS_LOG_DIRECTORY=$CUDA_MPS_LOG_DIRECTORY"
        if [ -n "$THREAD_PCT" ]; then echo "export CUDA_MPS_ACTIVE_THREAD_PERCENTAGE=$THREAD_PCT"; fi
    } > "$ENV_OUT"
    echo "  >> wrote worker env to $ENV_OUT  (workers:  source $ENV_OUT)"
}

if is_running; then
    if [ "$RESTART" = 1 ]; then
        echo ">> MPS already running — restarting (per --restart)."
        echo quit | nvidia-cuda-mps-control || true
        sleep 1
    else
        echo ">> MPS control daemon already running (pid: $(pgrep -x nvidia-cuda-mps-control | tr '\n' ' '))."
        echo "   pipe dir: $CUDA_MPS_PIPE_DIRECTORY   (use --restart to recreate)"
        write_env
        exit 0
    fi
fi

echo ">> Starting CUDA MPS control daemon on GPU(s) [$CUDA_VISIBLE_DEVICES]..."
nvidia-cuda-mps-control -d

# Confirm it came up
sleep 1
if ! is_running; then
    echo "ERROR: MPS daemon failed to start. Check $CUDA_MPS_LOG_DIRECTORY/control.log"; exit 1
fi
echo ">> MPS control daemon up (pid: $(pgrep -x nvidia-cuda-mps-control | tr '\n' ' '))."

# Optional SM cap per client (the server-side default; clients can still override
# via CUDA_MPS_ACTIVE_THREAD_PERCENTAGE). With K workers, ~100/K is a sane start.
if [ -n "$THREAD_PCT" ]; then
    echo "set_default_active_thread_percentage $THREAD_PCT" | nvidia-cuda-mps-control >/dev/null || true
    got=$(echo get_default_active_thread_percentage | nvidia-cuda-mps-control 2>/dev/null || true)
    echo ">> default active-thread cap set to ${got:-$THREAD_PCT}% per client."
fi

write_env

# Memory reminder (MPS shares, does not partition, GPU memory)
mem=$(nvidia-smi --query-gpu=memory.total --format=csv,noheader,nounits -i 0 2>/dev/null | head -1 || true)
echo ""
echo "######################################################################"
echo "### MPS READY on GPU [$CUDA_VISIBLE_DEVICES]${mem:+  (${mem} MiB total — shared across all workers)}"
echo "###   workers: source $ENV_OUT   then launch your training processes"
echo "###   verify : bash server_setup/mps_check.sh"
echo "###   stop   : echo quit | nvidia-cuda-mps-control"
echo "### Cap total worker memory (MPS does NOT isolate it) to avoid an OOM wedge."
echo "######################################################################"
